---
abstract: 'RFC close address list parsing'
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  JSON: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Email::Address::List
name: Email-Address-List
no_index:
  directory:
    - inc
    - t
requires:
  Email::Address: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
